export const CLICK_ON_CONTACTS_PAGE_LINK = "CLICK_ON_CONTACTS_PAGE_LINK"
export const CLICK_ON_ADD_CONTACT_LINK = "CLICK_ON_ADD_CONTACT_LINK"
//fetch contacts action types
export const FETCH_CONTACTS_BEGIN = "FETCH_CONTACTS_BEGIN"
export const FETCH_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS"
export const FETCH_CONTACTS_FAILURE = "FETCH_CONTACTS_FAILURE"

export const ADD_NEW_CONTACT = "ADD_NEW_CONTACT"
export const DELETE_CONTACT = "DELETE_CONTACT"
export const INPUT_CONTACT_NAME = "INPUT_CONTACT_NAME"
export const INPUT_CONTACT_NUMBER = "INPUT_CONTACT_NUMBER"
export const SEND_NOTIFICATION = "SEND_NOTIFICATION"
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION"

/**
 * actiontypes makes it easier to define and use actions. It is convention to use all caps.
 */